#!/bin/sh
# nft wrapper to load rules at startup and flush at shutdown

flush()
{
        echo "Got signal, stopping ..."
	nft flush ruleset
        exit 0
}

trap flush INT TERM QUIT EXIT

# Load ruleset
nft -f /etc/nftables.conf

# sleep may exit on known signal, so we cannot use 'set -e'
sleep infinity
