name: Container Claus

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  supervisor:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app: [curios, curios-httpd, curios-ntpd, curios-nftables]
    uses: ./.github/workflows/build-push.yml
    with:
      app: ${{ matrix.app }}
      ver: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
