name: Container Claus

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]*.*'
  workflow_dispatch:

jobs:
  container:
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        app: [system, httpd, ntpd, nftables, neofetch]
    uses: ./.github/workflows/build-push.yml
    with:
      app: ${{ matrix.app }}
      ver: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
